### PR TITLE
Fix breaking changes from latest version

### PR DESCRIPTION
**Pull request by rizwankce**

### CODE REVIEW

**Comment by rizwankce** [comment]
v0.6.8 have breaking changes so updating the demo app to have the latest update

**Comment by icanzilb** [comment]
Good catch! I didn't think to give the demo app a run after merging these changes, thanks

**Comment by rizwankce** [comment]
@icanzilb need a favour. 

Im participating in hacktoberfest. Every year I usually participate on October and use their plan a tree options from digital ocean. 

To make this PR count, it would be really helpful if you add `hacktoberfest-accepted` label to this PR. more info [here](https://hacktoberfest.com/participation/#pr-mr-details)

**Comment by icanzilb** [comment]
Sure @rizwankce not a problem at all

**Comment by rizwankce** [comment]
> Sure @rizwankce not a problem at all 

Thank you so much. Really appreciate!!

**Pull request merged**
